---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rtsp-stream-api
  name: rtsp-stream-api
  namespace: kms
#provisioner: kubernetes.io/aws-ebs
spec:
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 512Gi
 storageClassName: csi-rbd-sc