---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rtsp-stream-api
  name: rtsp-stream-api
  namespace: kms
spec:
  ports:
  - name: api
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: rtsp-stream-api
  sessionAffinity: None
  type: ClusterIP
